### ISSUE TITLE
Systemd starting command in README.md

### ISSUE THREAD

**Issue by MikeLeePoly** [matthewnourse/polite-hwclock-hctosys#2]
My teammate thinks the Systemd starting command in README.md should be this:
 `sudo systemctl start polite-hwclock-hctosys       # Systemd`

instead of 

`sudo service polite-hwclock-hctosys start         # Systemd`

Output:

```
[polite-hwclock-hctosys]$ sudo systemctl polite-hwclock-hctosys start
Unknown command verb polite-hwclock-hctosys.
```

This is in the Fedora Linux terminal after `wsl -d podman-machine-default` in my Windows CMD.

**Comment by matthewnourse** [comment]
Hi @MikeLeePoly, thanks for trying out `polite-hwclock-hctosys` and for raising this issue.

I see that under `Output` you're using `sudo systemctl polite-...` instead of `sudo service polite-...`  
I'd expect the `sudo systemctl ...` to fail but `sudo service` should work.
  
`service name verb` redirects to `systemctl verb name` on the distros I've come across.
Does `sudo service polite-hwclock-hctosys start` work for you?

I'm happy to update the README to cover both cases though.

Thanks again!

**Comment by MikeLeePoly** [comment]
> Hi @MikeLeePoly, thanks for trying out `polite-hwclock-hctosys` and for raising this issue.
> 
> I see that under `Output` you're using `sudo systemctl polite-...` instead of `sudo service polite-...` I'd expect the `sudo systemctl ...` to fail but `sudo service` should work.
> 
> `service name verb` redirects to `systemctl verb name` on the distros I've come across. Does `sudo service polite-hwclock-hctosys start` work for you?
> 
> I'm happy to update the README to cover both cases though.
> 
> Thanks again!

That doesn't work for my Fedora distro though

```
[user@ ~]$ sudo service polite-hwclock-hctosys start
sudo: service: command not found

[user@ ~]$ service
-bash: service: command not found
```

```
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="37 (Container Image)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Container Image"
VARIANT_ID=container
```

**Comment by MikeLeePoly** [comment]
Closing because this turns out to be just differences in Linux distributions.

**Comment by matthewnourse** [comment]
Thanks again @MikeLeePoly, I've updated the README.md now because I think the `systemctl` version of the command is correct in more distros.
