### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by rebroad** [matthewnourse/polite-hwclock-hctosys#3]
I'm noticing it's the main process at the top of "top", using 0.3% CPU... why does it need to be so active?

**Comment by matthewnourse** [comment]
Hi @rebroad, it needs to wake up once per second to have as much chance as possible to correct the time gradually rather than by a hard jump.  But I am surprised that it's using that much CPU.  I will take another look at it over the next few days.  Thanks for raising this issue.

**Comment by rebroad** [comment]
> Hi @rebroad, it needs to wake up once per second to have as much chance as possible to correct the time gradually rather than by a hard jump. But I am surprised that it's using that much CPU. I will take another look at it over the next few days. Thanks for raising this issue.

I would think that in some scenarios it can check less often, and also that it some scenarios it can jump in one go.

**Comment by matthewnourse** [comment]
> I would think that in some scenarios it can check less often, and also that it some scenarios it can jump in one go.

Possibly, though the trick is knowing when those scenarios are 😁 

The call to enable interrupts on the real-time-clock (`ioctl(fd, RTC_UIE_ON, 0)`) is far more expensive on my Ubuntu-over-WSL2 than on my Ubuntu-on-metal. 

I've made a code change to enable interrupts just once at startup, and this reduced CPU usage on my WSL2 system to the expected level.  The actual clock checking frequency is unchanged so I don't expect that this change will result in any loss of granularity.

I'm keen to hear if this new version also uses less CPU on your system.
